const mathDict = {
  ip: ['ip.cn/*'],
  cto: ['blog.51cto.com/*'],
  nga: ['nga.178.com/*', 'nga.178.com/*', 'bbs.ngacn.cc/*', 'bbs.ngacn.cc/*', 'bbs.nga.cn/*', 'bbs.nga.cn/*'],
  imooc: ['www.imooc.com/video/*'],
  baidu: ['www.baidu.com/*', 'www.baidu.com/*'],
  zhihu: [
    '.zhihu.com/*',
    'www.zhihu.com/question/*',
    'www.zhihu.com/*',
    'www.zhihu.com/*',
    'zhuanlan.zhihu.com/*',
    'zhuanlan.zhihu.com/*',
  ],
  youdao: ['dict.youdao.com*', 'dict.youdao.com*', 'fanyi.youdao.com/*', 'fanyi.youdao.com/*'],
  ruan: ['www.ruanyifeng.com/*'],
  wenku: ['wenku.baidu*'],
  qrCode: [
    'login.taobao.com/*',
    'login.1688.com/*',
    'account.aliyun.com/*',
    'passport.jd.com/*',
    'weibo.com/*',
    'login.tmall.com/*',
    'baidu.com/*',
    'graph.qq.com/*',
    'xui.ptlogin2.qq.com/*',
    'ssl.xui.ptlogin2.qq.com/*',
    'ui.ptlogin2.qq.com/*',
    'passport.suning.com/*',
    'zhihu.com/*',
    'douyu.com/*',
    'alipay.com/*',
    'passport.xiami.com/*',
    'passport.csdn.net/*',
  ],
  csdn: ['csdn.*/'],
}

export default mathDict
