const mathDict = {
  ip: ['ip.cn'],
  cto: ['blog.51cto.com'],
  nga: ['nga.178.com', 'nga.178.com', 'bbs.ngacn.cc', 'bbs.ngacn.cc', 'bbs.nga.cn', 'bbs.nga.cn'],
  imooc: ['imooc.com/video'],
  baidu: ['baidu.com', 'baidu.com'],
  'zhihu-ome': ['zhihu.com',],
  'zhihu-question': ['www.zhihu.com/question',],
  'zhihu-zhanlan': ['zhuanlan.zhihu.com',],
  'zhihu-zhanlan-p': ['zhuanlan.zhihu.com/p',],
  youdao: ['dict.youdao.com', 'dict.youdao.com', 'fanyi.youdao.com', 'fanyi.youdao.com'],
  ruan: ['ruanyifeng.com'],
  wenku: ['wenku.baidu'],
  qrCode: [
    'login.taobao.com',
    'login.1688.com',
    'account.aliyun.com',
    'passport.jd.com',
    'weibo.com',
    'login.tmall.com',
    'baidu.com',
    'graph.qq.com',
    'xui.ptlogin2.qq.com',
    'ssl.xui.ptlogin2.qq.com',
    'ui.ptlogin2.qq.com',
    'passport.suning.com',
    'zhihu.com',
    'douyu.com',
    'alipay.com',
    'passport.xiami.com',
    'passport.csdn.net',
  ],
  csdn: ['csdn.'],
  avgle: ['avgle.com/videos'],
  avgle_item: ['avgle.com/video'],
  'vue-cli': ['cli.vuejs.org', 'vuex.vuejs.org'],
  fanBaidu: ['fanyi.baidu.com'],
  jd: ['item.jd.com'],
  'zhihu-search': ['zhihu.com/search'],
  'zhihu-people': ['www.zhihu.com/people', 'www.zhihu.com/people'],
  'ty66-down': ['rmdown.com/link.php'],
  'ty66-page': ['t66y.com/htm_data'],
  '89File': ['http://www.89file.com/file'],
  '89FileDown': ['http://www.89file.com/down'],
  gogs: ['http://d.bjong.me:9546', 'gogs'],
  btdax: ['www.btdx8.com/douban_rating']
}

export default mathDict
