const mathDict = {
  ip: ['ip.cn'],
  wenku: ['wenku.baidu'],
  cto: ['blog.51cto.com'],
  zhihuHome: ['zhihu.com',],
  imooc: ['imooc.com/video'],
  ruan: ['www.ruanyifeng.com/'],
  baidu: ['baidu.com', 'baidu.com'],
  'zhihu-zhanlan': ['zhuanlan.zhihu.com',],
  'zhihu-zhanlan-p': ['zhuanlan.zhihu.com/p',],
  'zhihu-question': ['www.zhihu.com/question',],
  'zhihu-notifications': ['zhihu.com/notifications',],
  youdao: ['dict.youdao.com', 'dict.youdao.com', 'fanyi.youdao.com', 'fanyi.youdao.com'],
  nga: ['nga.178.com', 'nga.178.com', 'bbs.ngacn.cc', 'bbs.ngacn.cc', 'bbs.nga.cn', 'bbs.nga.cn'],
  qrCode: [
    'weibo.com',
    'baidu.com',
    'zhihu.com',
    'douyu.com',
    'alipay.com',
    'graph.qq.com',
    'login.1688.com',
    'passport.jd.com',
    'login.tmall.com',
    'login.taobao.com',
    'passport.csdn.net',
    'account.aliyun.com',
    'ui.ptlogin2.qq.com',
    'passport.xiami.com',
    'xui.ptlogin2.qq.com',
    'passport.suning.com',
    'ssl.xui.ptlogin2.qq.com',
  ],
  csdn: ['csdn.'],
  jd: ['item.jd.com'],
  jianshu: ['.jianshu.com'],
  'xiaozong': ['appinn.com'],
  avgle: ['avgle.com/videos'],
  jdSearch: ['search.jd.com'],
  fanBaidu: ['fanyi.baidu.com'],
  cssmoban: ['cssmoban.com'],
  avgle_item: ['avgle.com/video'],
  'ty66-page': ['t66y.com/htm_data'],
  segmentfault: ['segmentfault.com'],
  cilixiong: ['cilixiong.com/movie/'],
  googleSearch: ['google.com/search'],
  'zhihu-search': ['zhihu.com/search'],
  'ty66-down': ['rmdown.com/link.php'],
  btdax: ['www.btdx8.com/douban_rating'],
  cssmoban_tag: ['cssmoban.com/tags.asp'],
  '89File': ['http://www.89file.com/file'],
  gogs: ['http://d.bjong.me:9546', 'gogs'],
  movieDouban: ['movie.douban.com/explore'],
  crsoso: ['www.crsoso.me/search.html?name'],
  '89FileDown': ['http://www.89file.com/down'],
  iconfont: ['.iconfont.cn/manage/index?spm='],
  'vue-cli': ['cli.vuejs.org', 'vuex.vuejs.org'],
  wuerpojie: ['52pojie.cn/thread', '52pojie.cn/forum'],
  'zhihu-people': ['www.zhihu.com/people', 'www.zhihu.com/people'],
  engotozh: ['www.php.net/manual/en', 'developer.mozilla.org/en-US', 'eslint.org/', 'api.jquery.com/'],
}

export default mathDict
